version: '3'
services:
  database:
    image: 'postgres'
    env_file:
      - ./db/database.env
    volumes:
      - ./db/database-data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database-data: